const itemData = {
	items: [
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/s2GwS0N/umbrella-chair-around-swimming-pool.jpg",
			price: 120,
		},
		{
			name: " beautiful room",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Beach",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 120,
		},
		{
			name: "Beach resort",
			category_name: "Beach",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/G0T2NXh/b4f2-ho-00-p-1024x768.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Cabins",
			image: "https://i.ibb.co/NCS3Gkq/cabin-2.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Cabins",
			image: "https://i.ibb.co/Kbk3d0J/cabin.jpg",
			price: 120,
		},
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/s2GwS0N/umbrella-chair-around-swimming-pool.jpg",
			price: 120,
		},
		{
			name: " beautiful room",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Beach",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 120,
		},
		{
			name: "Beach resort",
			category_name: "Beach",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/G0T2NXh/b4f2-ho-00-p-1024x768.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Cabins",
			image: "https://i.ibb.co/NCS3Gkq/cabin-2.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Cabins",
			image: "https://i.ibb.co/Kbk3d0J/cabin.jpg",
			price: 120,
		},
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/s2GwS0N/umbrella-chair-around-swimming-pool.jpg",
			price: 120,
		},
		{
			name: " beautiful room",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Beach",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 120,
		},
		{
			name: "Beach resort",
			category_name: "Beach",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/G0T2NXh/b4f2-ho-00-p-1024x768.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Cabins",
			image: "https://i.ibb.co/NCS3Gkq/cabin-2.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Cabins",
			image: "https://i.ibb.co/Kbk3d0J/cabin.jpg",
			price: 120,
		},
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/s2GwS0N/umbrella-chair-around-swimming-pool.jpg",
			price: 120,
		},
		{
			name: " beautiful room",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Beach",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 120,
		},
		{
			name: "Beach resort",
			category_name: "Beach",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/G0T2NXh/b4f2-ho-00-p-1024x768.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Cabins",
			image: "https://i.ibb.co/NCS3Gkq/cabin-2.jpg",
			price: 120,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Cabins",
			image: "https://i.ibb.co/Kbk3d0J/cabin.jpg",
			price: 120,
		},
	],
};

module.exports = itemData;
