const itemData = {
	items: [
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 44,
			property_type: "house",
			location: "Indonasia",
			room: 1,
			bed: 2,
			bathroom: 1,
		},
		{
			name: " beautiful room",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 1,
			bed: 1,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Beach",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 60,
			property_type: "apartment",
			location: "Indonasia",
			room: 5,
			bed: 8,
			bathroom: 4,
		},
		{
			name: "Beach resort",
			category_name: "Beach",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 170,
			property_type: "house",
			location: "Indonasia",
			room: 7,
			bed: 10,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 53,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 77,
			property_type: "hostel",
			location: "Indonasia",
			room: 4,
			bed: 4,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 24,
			property_type: "house",
			location: "france",
			room: 2,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/G0T2NXh/b4f2-ho-00-p-1024x768.jpg",
			price: 63,
			property_type: "apartment",
			location: "india",
			room: 3,
			bed: 6,
			bathroom: 3,
		},
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 44,
			property_type: "house",
			location: "Indonasia",
			room: 1,
			bed: 2,
			bathroom: 1,
		},
		{
			name: " beautiful room",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 1,
			bed: 1,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Beach",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 60,
			property_type: "apartment",
			location: "Indonasia",
			room: 5,
			bed: 8,
			bathroom: 4,
		},
		{
			name: "Beach resort",
			category_name: "Beach",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 170,
			property_type: "house",
			location: "Indonasia",
			room: 7,
			bed: 10,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 53,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 77,
			property_type: "hostel",
			location: "Indonasia",
			room: 4,
			bed: 4,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 24,
			property_type: "house",
			location: "france",
			room: 2,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/G0T2NXh/b4f2-ho-00-p-1024x768.jpg",
			price: 63,
			property_type: "apartment",
			location: "india",
			room: 3,
			bed: 6,
			bathroom: 3,
		},
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 44,
			property_type: "house",
			location: "Indonasia",
			room: 1,
			bed: 2,
			bathroom: 1,
		},
		{
			name: " beautiful room",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 1,
			bed: 1,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Beach",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 60,
			property_type: "apartment",
			location: "Indonasia",
			room: 5,
			bed: 8,
			bathroom: 4,
		},
		{
			name: "Beach resort",
			category_name: "Beach",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 170,
			property_type: "house",
			location: "Indonasia",
			room: 7,
			bed: 10,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 53,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 77,
			property_type: "hostel",
			location: "Indonasia",
			room: 4,
			bed: 4,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 24,
			property_type: "house",
			location: "france",
			room: 2,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/G0T2NXh/b4f2-ho-00-p-1024x768.jpg",
			price: 63,
			property_type: "apartment",
			location: "india",
			room: 3,
			bed: 6,
			bathroom: 3,
		},
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 44,
			property_type: "house",
			location: "Indonasia",
			room: 1,
			bed: 2,
			bathroom: 1,
		},
		{
			name: " beautiful room",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 1,
			bed: 1,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Beach",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 60,
			property_type: "apartment",
			location: "Indonasia",
			room: 5,
			bed: 8,
			bathroom: 4,
		},
		{
			name: "Beach resort",
			category_name: "Beach",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 170,
			property_type: "house",
			location: "Indonasia",
			room: 7,
			bed: 10,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 53,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 77,
			property_type: "hostel",
			location: "Indonasia",
			room: 4,
			bed: 4,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 24,
			property_type: "house",
			location: "france",
			room: 2,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/G0T2NXh/b4f2-ho-00-p-1024x768.jpg",
			price: 63,
			property_type: "apartment",
			location: "india",
			room: 3,
			bed: 6,
			bathroom: 3,
		},
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 44,
			property_type: "house",
			location: "Indonasia",
			room: 1,
			bed: 2,
			bathroom: 1,
		},
		{
			name: " beautiful room",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 3,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Beach",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 60,
			property_type: "apartment",
			location: "Indonasia",
			room: 5,
			bed: 8,
			bathroom: 4,
		},
		{
			name: "Beach resort",
			category_name: "Beach",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 170,
			property_type: "house",
			location: "Indonasia",
			room: 7,
			bed: 10,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 53,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 77,
			property_type: "hostel",
			location: "Indonasia",
			room: 4,
			bed: 4,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 24,
			property_type: "house",
			location: "france",
			room: 2,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/G0T2NXh/b4f2-ho-00-p-1024x768.jpg",
			price: 63,
			property_type: "apartment",
			location: "india",
			room: 3,
			bed: 6,
			bathroom: 3,
		},
		{
			name: "Tropical beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 44,
			property_type: "house",
			location: "Indonasia",
			room: 1,
			bed: 2,
			bathroom: 1,
		},
		{
			name: " beautiful room",
			category_name: "Rooms",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 120,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 1,
			bed: 1,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Beach",
			image: "https://i.ibb.co/v4c0krk/images.jpg",
			price: 60,
			property_type: "apartment",
			location: "Indonasia",
			room: 5,
			bed: 8,
			bathroom: 4,
		},
		{
			name: "Beach resort",
			category_name: "Beach",
			image: "https://i.ibb.co/Zctb5pF/Miavana3-A-Private-Villas-scaled-1.jpg",
			price: 170,
			property_type: "house",
			location: "Indonasia",
			room: 7,
			bed: 10,
			bathroom: 3,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Mansions",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 53,
			property_type: "guesthouse",
			location: "Indonasia",
			room: 2,
			bed: 4,
			bathroom: 2,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Caves",
			image: "https://i.ibb.co/Rc1fYB8/sunset-pool.jpg",
			price: 77,
			property_type: "hostel",
			location: "Indonasia",
			room: 4,
			bed: 4,
			bathroom: 1,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/kXT25Hk/constance-belle-mare-plage-1.jpg",
			price: 24,
			property_type: "house",
			location: "france",
			room: 7,
			bed: 14,
			bathroom: 5,
		},
		{
			name: "BALIAN TREEHOUSE w beautiful pool",
			category_name: "Tropical",
			image: "https://i.ibb.co/G0T2NXh/b4f2-ho-00-p-1024x768.jpg",
			price: 63,
			property_type: "apartment",
			location: "india",
			room: 3,
			bed: 6,
			bathroom: 3,
		},
	],
};

module.exports = itemData;
